[package]
name = "mars_calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde="1.0.137"
serde_derive="1.0.138"
serde_json="1.0.82"
rand = "0.8.5"

